### PR TITLE
Updated text to address multiple issues

### PR DESCRIPTION
**Pull request by SimonFrost-Arm**
Issue #8 - use of 'PSA Attester'
Issue #4 - statement on multiple measurements contributing to RIM Issue #3 - optionality of verification service indicator Typo in profile tag for 'cca' - should have been 'cca_platform'

### CODE REVIEW

**Comment by SimonFrost-Arm** [comment]
For reason I've yet to figure out, don't seem to be able to add Giri as a reviewer to this PR

**Comment by SimonFrost-Arm** [comment]
Outstanding line length & Ref failing checks noted.

**Comment by thomas-fossati** [comment]
> For reason I've yet to figure out, don't seem to be able to add Giri as a reviewer to this PR

Did you invite him as a collaborator?  If so, did he accept the invitation?
If both conditions hold, you should see him appear in the "reviewers" drop-down menu.

**Review by thomas-fossati — APPROVED** [review]
thanks!

**Comment by SimonFrost-Arm** [comment]
Merged - will add another change for format issues

**Pull request merged**
